F4::
loop, 55555
{
SendInput GET GOOD - GET SPERMAWARE GET GOOD - GET SPERMAWARE GET GOOD - GET SPERMAWARE GET GOOD - GET SPERMAWARE GET GOOD - GET SPERMAWARE GET GOOD - GET SPERMAWARE
SendInput {enter}
Sleep 1
}
return
F5::
reload
return
